# dir declaration
MID_HTTP_PARSER_DIR = $(EMBARC_ROOT)/middleware/http_parser

MID_HTTP_PARSER_ASMSRCDIR	=
MID_HTTP_PARSER_CSRCDIR	= $(MID_HTTP_PARSER_DIR)

MID_HTTP_PARSER_INCDIR	= $(MID_HTTP_PARSER_DIR)

MID_INCDIR += $(MID_HTTP_PARSER_INCDIR)
MID_CSRCDIR += $(MID_HTTP_PARSER_CSRCDIR)
MID_ASMSRCDIR += $(MID_HTTP_PARSER_ASMSRCDIR)

# the dir to generate objs
MID_HTTP_PARSER_OBJDIR	= $(OUT_DIR)/middleware/http_parser

# find all the srcs in the target dirs
MID_HTTP_PARSER_CSRCS = $(call get_csrcs, $(MID_HTTP_PARSER_CSRCDIR))
MID_HTTP_PARSER_ASMSRCS = $(call get_asmsrcs, $(MID_HTTP_PARSER_ASMSRCDIR))

# get obj files
MID_HTTP_PARSER_COBJS = $(call get_objs, $(MID_HTTP_PARSER_CSRCS), $(MID_HTTP_PARSER_OBJDIR))
MID_HTTP_PARSER_ASMOBJS = $(call get_objs, $(MID_HTTP_PARSER_ASMSRCS), $(MID_HTTP_PARSER_OBJDIR))

# include dependency files
ifneq ($(MAKECMDGOALS),clean)
 -include $(MID_HTTP_PARSER_COBJS:.o=.o.d) $(MID_HTTP_PARSER_ASMOBJS:.o=.o.d)
endif

# genearte library
MID_LIB_HTTP_PARSER = $(OUT_DIR)/libmidhttp_parser.a
MID_LIBS += $(MID_LIB_HTTP_PARSER)

$(MID_LIB_HTTP_PARSER): $(MID_HTTP_PARSER_OBJDIR) $(MID_HTTP_PARSER_COBJS) $(MID_HTTP_PARSER_ASMOBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(MID_HTTP_PARSER_COBJS) $(MID_HTTP_PARSER_ASMOBJS)

# specific compile rules
.SECONDEXPANSION:
$(MID_HTTP_PARSER_COBJS): $(MID_HTTP_PARSER_OBJDIR)/%.o : $(call get_c_prerequisite, $(MID_HTTP_PARSER_CSRCDIR)) $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $(MID_HTTP_PARSER_COMPILE_OPT) $< -o $@

.SECONDEXPANSION:
$(MID_HTTP_PARSER_ASMOBJS): $(MID_HTTP_PARSER_OBJDIR)/%.o : $(call get_asm_prerequisite, $(MID_HTTP_PARSER_ASMSRCDIR)) $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_ASSEMBLE)
	$(Q)$(CC) -c $(ASM_OPT) $(MID_HTTP_PARSER_COMPILE_OPT) $< -o $@

# generate obj dir
$(MID_HTTP_PARSER_OBJDIR):
	$(TRACE_CREATE_DIR)
	$(Q)$(MKD) $(subst /,$(PS),$@)

# Middleware Definitions
MID_HTTP_PARSER_DEFINES = -DMID_HTTP_PARSER
MID_DEFINES += $(MID_HTTP_PARSER_DEFINES)