# dir declaration
MID_MATRIXSSL_DIR = $(EMBARC_ROOT)/middleware/matrixssl

MID_MATRIXSSL_ASMSRCDIR	=

MID_MATRIXSSL_CSRCDIR	= $(MID_MATRIXSSL_DIR)/core/embARC \
				$(MID_MATRIXSSL_DIR)/core \
				$(MID_MATRIXSSL_DIR)/crypto/digest \
				$(MID_MATRIXSSL_DIR)/crypto/keyformat \
				$(MID_MATRIXSSL_DIR)/crypto/layer \
				$(MID_MATRIXSSL_DIR)/crypto/math \
				$(MID_MATRIXSSL_DIR)/crypto/pubkey \
				$(MID_MATRIXSSL_DIR)/crypto/symmetric \
				$(MID_MATRIXSSL_DIR)/crypto/prng \
				$(MID_MATRIXSSL_DIR)/matrixssl
MID_MATRIXSSL_INCDIR	= $(MID_MATRIXSSL_DIR)

MID_INCDIR += $(MID_MATRIXSSL_INCDIR)
MID_CSRCDIR += $(MID_MATRIXSSL_CSRCDIR)
MID_ASMSRCDIR += $(MID_MATRIXSSL_ASMSRCDIR)

# the dir to generate objs
MID_MATRIXSSL_OBJDIR = $(OUT_DIR)/middleware/matrixssl

# find all the srcs in the target dirs
MID_MATRIXSSL_CSRCS = $(call get_csrcs, $(MID_MATRIXSSL_CSRCDIR))
MID_MATRIXSSL_ASMSRCS = $(call get_asmsrcs, $(MID_MATRIXSSL_ASMSRCDIR))

MID_MATRIXSSL_COBJS = $(call get_objs, $(MID_MATRIXSSL_CSRCS), $(MID_MATRIXSSL_OBJDIR))
MID_MATRIXSSL_ASMOBJS = $(call get_objs, $(MID_MATRIXSSL_ASMSRCS), $(MID_MATRIXSSL_OBJDIR))

# include dependency files
ifneq ($(MAKECMDGOALS),clean)
 -include $(MID_MATRIXSSL_COBJS:.o=.o.d) $(MID_MATRIXSSL_ASMOBJS:.o=.o.d)
endif

# genearte library
MID_LIB_MATRIXSSL = $(OUT_DIR)/libmidmatrixssl.a
MID_LIBS += $(MID_LIB_MATRIXSSL)

$(MID_LIB_MATRIXSSL): $(MID_MATRIXSSL_OBJDIR) $(MID_MATRIXSSL_COBJS) $(MID_MATRIXSSL_ASMOBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(MID_MATRIXSSL_COBJS) $(MID_MATRIXSSL_ASMOBJS)

# specific compile rules
.SECONDEXPANSION:
$(MID_MATRIXSSL_COBJS): $(MID_MATRIXSSL_OBJDIR)/%.o :$(call get_c_prerequisite, $(MID_MATRIXSSL_CSRCDIR)) $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $(MID_MATRIXSSL_COMPILE_OPT) $< -o $@

.SECONDEXPANSION:
$(MID_MATRIXSSL_ASMOBJS): $(MID_MATRIXSSL_OBJDIR)/%.o :$(call get_asm_prerequisite, $(MID_MATRIXSSL_ASMSRCDIR)) $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_ASSEMBLE)
	$(Q)$(CC) -c $(ASM_OPT) $(MID_MATRIXSSL_COMPILE_OPT) $< -o $@

# generate obj dir
$(MID_MATRIXSSL_OBJDIR):
	$(TRACE_CREATE_DIR)
	$(Q)$(MKD) $(subst /,$(PS),$@)

# Middleware Definitions
MID_MATRIXSSL_DEFINES = -DMID_MATRIXSSL -D__OPTIMIZE__ -D__OPTIMIZE_SIZE__
MID_DEFINES += $(MID_MATRIXSSL_DEFINES)


