embARC: arc_exception.h File Reference
arc_exception.h File Reference
ARC HAL » Exception and Interrupt » CPU ExceptionARC HAL » Exception and Interrupt » | Interrupt
header file of exception and interrupt management module
#include "embARC_toolchain.h"
#include "arc.h"
#include "arc_builtin.h"
Data Structures
struct int_exc_frame
struct callee_frame
struct processor_frame
Macros
#define NUM_EXC_CPU 16
#define NUM_EXC_INT 9
#define NUM_EXC_ALL (NUM_EXC_CPU + NUM_EXC_INT)
#define ARC_PROCESSOR_FRAME_SIZE (sizeof(PROCESSOR_FRAME) / sizeof(uint32_t))
#define ARC_EXC_FRAME_SIZE (sizeof(INT_EXC_FRAME) / sizeof(uint32_t))
#define ARC_CALLEE_FRAME_SIZE (sizeof(CALLEE_FRAME) / sizeof(uint32_t))
#define INT_PRI_MIN (-2)
#define INT_PRI_MAX (-1)
#define NUM_INT_ALL NUM_EXC_INT
Typedefs
typedef struct int_exc_frame INT_EXC_FRAME
typedef struct callee_frame CALLEE_FRAME
typedef struct processor_frame PROCESSOR_FRAME
typedef void(* EXC_ENTRY)(void)
the data type for exception entry
typedef void(* EXC_HANDLER)(void *exc_frame)
the data type for exception handler
typedef void(* INT_HANDLER)(void *ptr)
the data type for interrupt handler
Functions
Inline void exc_vector_base_write (const void *vec_base)
write the exception vector base
Inline uint32_t exc_vector_base_read (void)
read current exception vector base
Inline uint32_t exc_sense (void)
sense whether in exc/interrupt processing
Inline void int_disable (const uint32_t intno)
disable the specific interrupt
Inline void int_enable (const uint32_t intno)
enable the specific int
Inline uint32_t int_enabled (const uint32_t intno)
check whether the specific int is enabled
Inline int32_t int_ipm_get (void)
get the interrupt priority mask
Inline void int_ipm_set (int intpri)
set the interrupt priority mask
Inline int32_t int_pri_get (const uint32_t intno)
get current interrupt priority mask
Inline uint32_t int_probe (const uint32_t intno)
probe the pending status of interrupt
Inline void int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
Inline void int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
Inline void cpu_lock (void)
lock cpu, disable interrupts
Inline void cpu_unlock (void)
unlock cpu, enable interrupts to happen
Inline uint32_t cpu_lock_save (void)
lock cpu and staus
Inline void cpu_unlock_restore (const uint32_t status)
unlock cpu with the specific status
const char * exc_no2string (uint32_t exc_no)
convert exception number to name
void exc_int_init (void)
intialize the exception and interrupt handling
int32_t exc_entry_install (const uint32_t excno, EXC_ENTRY entry)
install a CPU exception entry
EXC_ENTRY exc_entry_get (const uint32_t excno)
get the installed CPU exception entry
int32_t exc_handler_install (const uint32_t excno, EXC_HANDLER handler)
install an exception handler
EXC_HANDLER exc_handler_get (const uint32_t excno)
get the installed exception handler
int32_t int_handler_install (const uint32_t intno, INT_HANDLER handler)
install an interrupt handler
INT_HANDLER int_handler_get (const uint32_t intno)
get the installed an interrupt handler
void int_pri_set (const uint32_t intno, int32_t intpri)
set interrupt priority
void _arc_reset (void)
the reset entry
void exc_entry_cpu (void)
the default CPU exception entry
void exc_entry_firq (void)
the fast interrupt exception entry
void exc_entry_int (void)
the interrupt exception entry
Variables
uint32_t exc_nest_count
the counter for exc/int processing, =0 no int/exc >1 in int/exc processing
EXC_ENTRY exc_entry_table [NUM_EXC_ALL]
exception entry table
EXC_HANDLER exc_int_handler_table [NUM_EXC_ALL]
the cpu exception and interrupt exception handler table called in exc_entry_default and exc_entry_int
Detailed Description
header file of exception and interrupt management module
Definition in file arc_exception.h.
Function Documentation
const char* exc_no2string (uint32_t exc_no)
convert exception number to name
Parameters
exc_no exception number
Returns
exception name description
Definition at line 304 of file arc_exception.c.
References NUM_EXC_CPU.
Referenced by exc_handler_default().
void int_pri_set (const uint32_t intno, int32_t intpri)
set interrupt priority
Parameters
[in] intno interrupt number
[in] intpri interrupt priority
Definition at line 286 of file arc_exception.c.
References AUX_IRQ_PRIORITY, AUX_IRQ_SELECT, cpu_lock_save(), cpu_unlock_restore(), and INT_PRI_MIN.
Referenced by main().