embARC: Interrupt
Interrupt
ARC HAL » Exception and Interrupt
Interrupt related definitions.
Files
file arc_exception.c
C Implementation of exception and interrupt management.
file arc_exception.h
header file of exception and interrupt management module
Macros
#define INT_PRI_MIN (-2)
#define INT_PRI_MAX (-1)
#define NUM_INT_ALL NUM_EXC_INT
Typedefs
typedef void(* INT_HANDLER)(void *ptr)
the data type for interrupt handler
Functions
static void int_handler_default (void *p_excinf)
default interrupt handler
void exc_int_init (void)
intialize the exception and interrupt handling
int32_t int_handler_install (const uint32_t intno, INT_HANDLER handler)
install an interrupt handler
INT_HANDLER int_handler_get (const uint32_t intno)
get the installed an interrupt handler
Inline void int_disable (const uint32_t intno)
disable the specific interrupt
Inline void int_enable (const uint32_t intno)
enable the specific int
Inline uint32_t int_enabled (const uint32_t intno)
check whether the specific int is enabled
Inline int32_t int_ipm_get (void)
get the interrupt priority mask
Inline void int_ipm_set (int intpri)
set the interrupt priority mask
Inline int32_t int_pri_get (const uint32_t intno)
get current interrupt priority mask
Inline uint32_t int_probe (const uint32_t intno)
probe the pending status of interrupt
Inline void int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
Inline void int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
Inline void cpu_lock (void)
lock cpu, disable interrupts
Inline void cpu_unlock (void)
unlock cpu, enable interrupts to happen
Inline uint32_t cpu_lock_save (void)
lock cpu and staus
Inline void cpu_unlock_restore (const uint32_t status)
unlock cpu with the specific status
Detailed Description
Interrupt related definitions.
Macro Definition Documentation
#define INT_PRI_MAX (-1)
the maximum interrupt priority
Definition at line 165 of file arc_exception.h.
Referenced by exc_int_init().
#define INT_PRI_MIN (-2)
the minimum interrupt priority
Definition at line 162 of file arc_exception.h.
Referenced by exc_int_init(), int_ipm_get(), int_ipm_set(), int_pri_get(), int_pri_set(), and main().
#define NUM_INT_ALL NUM_EXC_INT
total number of interrupts
Definition at line 166 of file arc_exception.h.
Function Documentation
Inline uint32_t cpu_lock_save (void)
lock cpu and staus
Returns
cpu status
Definition at line 306 of file arc_exception.h.
References _arc_clri.
Referenced by dcache_flush(), dcache_flush_line(), dcache_flush_mlines(), dcache_invalidate(), dcache_invalidate_mlines(), dcache_lock_mlines(), exc_entry_install(), exc_int_init(), icache_invalidate_mlines(), icache_lock_mlines(), int_pri_set(), rw009_cmd(), and spi_send_cmd().
Inline void cpu_unlock_restore (const uint32_t status)
unlock cpu with the specific status
Parameters
[in] status cpu status saved by cpu_lock_save
Definition at line 316 of file arc_exception.h.
References _arc_seti.
Referenced by dcache_flush(), dcache_flush_line(), dcache_flush_mlines(), dcache_invalidate(), dcache_invalidate_mlines(), dcache_lock_mlines(), exc_entry_install(), exc_int_init(), icache_invalidate_mlines(), icache_lock_mlines(), int_pri_set(), rw009_cmd(), and spi_send_cmd().
Inline void int_disable (const uint32_t intno)
disable the specific interrupt
Parameters
[in] intno interrupt number
Definition at line 172 of file arc_exception.h.
References AUX_IRQ_ENABLE, and AUX_IRQ_SELECT.
Referenced by dw_gpio_close(), dw_gpio_control(), dw_gpio_open(), dw_iic_dis_cbr(), dw_iic_disable_interrupt(), dw_spi_dis_cbr(), dw_spi_disable_interrupt(), dw_uart_dis_cbr(), dw_uart_disable_interrupt(), emsk_timer_init(), main(), and nsim_timer_init().
Inline void int_enable (const uint32_t intno)
enable the specific int
Parameters
[in] intno interrupt number
Definition at line 183 of file arc_exception.h.
References AUX_IRQ_ENABLE, and AUX_IRQ_SELECT.
Referenced by dw_gpio_control(), dw_iic_ena_cbr(), dw_iic_enable_interrupt(), dw_spi_ena_cbr(), dw_spi_enable_interrupt(), dw_uart_ena_cbr(), dw_uart_enable_interrupt(), emsk_timer_init(), main(), and nsim_timer_init().
Inline uint32_t int_enabled (const uint32_t intno)
check whether the specific int is enabled
Parameters
[in] intno interrupt number
Returns
0 disabled, 1 enabled
Definition at line 195 of file arc_exception.h.
References AUX_IRQ_ENABLE, and AUX_IRQ_SELECT.
static void int_handler_default (void * p_excinf) static
default interrupt handler
Parameters
[in] p_excinf information for interrupt handler
Definition at line 91 of file arc_exception.c.
References AUX_ERRET, and AUX_IRQ_CAUSE.
INT_HANDLER int_handler_get (const uint32_t intno)
get the installed an interrupt handler
Parameters
[in] intno interrupt number
Returns
the installed interrupt handler or NULL
Definition at line 271 of file arc_exception.c.
References NUM_EXC_ALL, and NUM_EXC_CPU.
int32_t int_handler_install (const uint32_t intno, INT_HANDLER handler)
install an interrupt handler
Parameters
[in] intno interrupt number
[in] handler interrupt handler to install
Definition at line 254 of file arc_exception.c.
References NUM_EXC_ALL, and NUM_EXC_CPU.
Referenced by dw_gpio_open(), dw_iic_enable_interrupt(), dw_iic_open(), dw_spi_enable_interrupt(), dw_spi_open(), dw_uart_enable_interrupt(), dw_uart_open(), emsk_timer_init(), main(), and nsim_timer_init().
Inline int32_t int_ipm_get (void)
get the interrupt priority mask
Returns
interrupt priority mask, negative num
Definition at line 206 of file arc_exception.h.
References INT_PRI_MIN.
Inline void int_ipm_set (int intpri)
set the interrupt priority mask
Parameters
[in] intpri interrupt priority
Definition at line 220 of file arc_exception.h.
References INT_PRI_MIN.
Referenced by exc_int_init().
Inline void int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
Parameters
[in] intno interrupt number
[in] level,0-level trigger, 1-pluse triggered
Definition at line 277 of file arc_exception.h.
References AUX_IRQ_SELECT, and AUX_IRQ_TRIGGER.
Inline int32_t int_pri_get (const uint32_t intno)
get current interrupt priority mask
Parameters
[in] intno interrupt number
Definition at line 239 of file arc_exception.h.
References AUX_IRQ_PRIORITY, AUX_IRQ_SELECT, and INT_PRI_MIN.
Inline uint32_t int_probe (const uint32_t intno)
probe the pending status of interrupt
Parameters
[in] intno interrupt number
Returns
1 pending, 0 no pending
Definition at line 255 of file arc_exception.h.
References AUX_IRQ_PENDING, and AUX_IRQ_SELECT.
Inline void int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
Parameters
[in] intno interrupt number
Definition at line 266 of file arc_exception.h.
References AUX_IRQ_HINT.